//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiOnline.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangTablet
    {
        public int ID { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Tablet Tablet { get; set; }
    }
}
