//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiOnline.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangLaptops = new HashSet<ChiTietDonHangLaptop>();
            this.ChiTietDonHangPhones = new HashSet<ChiTietDonHangPhone>();
            this.ChiTietDonHangTablets = new HashSet<ChiTietDonHangTablet>();
        }
    
        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string TenNhanVien { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangLaptop> ChiTietDonHangLaptops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangPhone> ChiTietDonHangPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangTablet> ChiTietDonHangTablets { get; set; }
    }
}
