//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiOnline.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laptop()
        {
            this.ChiTietDonHangLaptops = new HashSet<ChiTietDonHangLaptop>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> GiaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnhSanPham { get; set; }
        public string MoTaSanPham { get; set; }
        public string IDLoaiSanPham { get; set; }
        public string ManHinh { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HardDrive { get; set; }
        public string VGA { get; set; }
        public string Connection { get; set; }
        public string HDH { get; set; }
        public Nullable<double> Nang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangLaptop> ChiTietDonHangLaptops { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
