//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiOnline.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThietBiOnlineEntities : DbContext
    {
        public ThietBiOnlineEntities()
            : base("name=ThietBiOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHangLaptop> ChiTietDonHangLaptops { get; set; }
        public virtual DbSet<ChiTietDonHangPhone> ChiTietDonHangPhones { get; set; }
        public virtual DbSet<ChiTietDonHangTablet> ChiTietDonHangTablets { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<Laptop> Laptops { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Tablet> Tablets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
